version: "3"

services:
  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ../src:/var/www
  nginx:
    build:
      context: ./nginx
    volumes:
      - ../src:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - 8080:80
      - "433:433"
    depends_on:
      - php-fpm
  database:
    build:
      context: ./database
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - ./database/data/:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - '8000:80'
    restart: always
    environment:
        PMA_HOST: database
    depends_on:
        - database
